### PR TITLE
Yolo

### PR DESCRIPTION
**Pull request by chris-erickson**

### CODE REVIEW

**Comment by tybritten** [comment]
LGTM haha

**Comment by rowanseymour** [comment]
Hey guys, just a little explanation on what state you'll be in after this merge:

 - all flows run in mailroom (the old engine code is only there for unit tests)
 - USSD is gone for now
 - users in the "Alpha" group have the option to create flows with the new editor
 - importing of new editor flows doesn't work yet

Today or tomorrow we're going to merge https://github.com/nyaruka/rapidpro/pull/2397 which fixes imports and enables the new editor for everyone

**Comment by chris-erickson** [comment]
@rowanseymour thanks for the heads up.  Should we just wait for that before we deploy?  We're super far behind so this is going to be a bit of an experiment..

**Comment by rowanseymour** [comment]
@chris-erickson no I'd get started on getting up to date now - just bear in mind that you won't be able to do imports of new (i.e. created in the new editor) flows, and you'll need to add yourself to the Alpha user group to get access to the new editor. But those changes are coming asap, and what you are merging here is what we are currently running in prod.

Don't forget to all update your rp-indexer, courier and mailroom instances too!

**Comment by chris-erickson** [comment]
Great.  Working out our upgrade path for everything.  Indexer is done, archiver is done (throwing errors still, but haven't gotten around to that yet).  Getting things set to bring mailroom up to current (while running zero workers) then RP update, then turn it back on.  I look forward to not falling behind again soon 😃.

**Comment by rowanseymour** [comment]
godspeed...

**Pull request merged**
